In [2]:
import sys
import numpy as np

In [3]:
np.array([1, 4, 9, 3])

array([1, 4, 9, 3])

In [4]:
a = np.array([1, 4, 9, 3])

In [5]:
b = np.array([3, 2, 4, 1])

In [6]:
a[0], a[1]

(1, 4)

In [7]:
a[0:]

array([1, 4, 9, 3])

In [8]:
a[1:3]

array([4, 9])

In [9]:
a[1: -1]

array([4, 9])

In [10]:
a[::2]

array([1, 9])

In [11]:
b

array([3, 2, 4, 1])

In [12]:
b[0], b[2], b[-1]

(3, 4, 1)

In [14]:
b[[0, 2, -1]]

array([3, 4, 1])

In [15]:
a.dtype

dtype('int32')

In [16]:
b.dtype

dtype('int32')

In [20]:
c = np.array(['a', 'b', 'c'])

In [21]:
c.dtype

dtype('<U1')

In [22]:
A = np.array([[1, 3, 4, 1], [1, 9, 7, 4]])

In [23]:
A

array([[1, 3, 4, 1],
       [1, 9, 7, 4]])

In [24]:
A.shape

(2, 4)

In [25]:
A.ndim

2

In [26]:
A.size

8

In [27]:
A[1]

array([1, 9, 7, 4])

In [28]:
A[0]

array([1, 3, 4, 1])

In [32]:
A[: 1]

array([[1, 3, 4, 1]])

In [31]:
A

array([[1, 3, 4, 1],
       [3, 3, 3, 3]])

In [33]:
A.sum()

21

In [34]:
a.sum()

17

In [35]:
a.mean()

4.25

In [36]:
A.mean()

2.625

In [37]:
A.std()

0.9921567416492215

In [38]:
a.std()

2.947456530637899

In [39]:
a.var()

8.6875

In [40]:
A.var()

0.984375

In [41]:
A.sum(axis=0)

array([4, 6, 7, 4])

In [43]:
a = np.arange(5)

In [44]:
a

array([0, 1, 2, 3, 4])

In [45]:
a + 10

array([10, 11, 12, 13, 14])

In [46]:
a - 10

array([-10,  -9,  -8,  -7,  -6])

In [47]:
a * 2

array([0, 2, 4, 6, 8])

In [50]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [51]:
a + b

array([0, 2, 4, 6, 8])

In [52]:
a * b

array([ 0,  1,  4,  9, 16])

In [53]:
a[[0, -1]]

array([0, 4])

In [54]:
a[[True, False, False, True, True]]

array([0, 3, 4])

In [55]:
a >= 2

array([False, False,  True,  True,  True])

In [56]:
a <= 2

array([ True,  True,  True, False, False])

In [57]:
a[a >= 2]

array([2, 3, 4])

In [58]:
a.mean()

2.0

In [59]:
a[a > a.mean()]

array([3, 4])

In [60]:
a[~(a > a.mean())]

array([0, 1, 2])

In [61]:
a[(a <= 2) | (a == 1)]

array([0, 1, 2])

In [64]:
a[(a == 2) & (a % 2 == 0)]

array([2])

In [65]:
A = np.random.randint(100, size=(3, 3))

In [66]:
A

array([[18, 39, 92],
       [35, 64,  0],
       [29, 38, 74]])

In [67]:
l = list(range(1000))

In [68]:
a = np.arange(10000)

In [72]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


332833500

In [73]:
%time sum([x == 2 for x in l])

CPU times: total: 0 ns
Wall time: 0 ns


1

In [75]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [80]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [82]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [83]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [84]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [85]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [89]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [90]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [91]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [92]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])