In [1]:
import sys
import numpy as np

In [2]:
A = np.array([
    [1, 3, 4],
    [3, 5, 1],
    [4, 9, 1]
])

In [3]:
A

array([[1, 3, 4],
       [3, 5, 1],
       [4, 9, 1]])

In [4]:
B = np.array([
    [4, 9, 1],
    [3, 1, 7],
    [3, 5, 8]
])

In [5]:
B

array([[4, 9, 1],
       [3, 1, 7],
       [3, 5, 8]])

In [6]:
A.dot(B)

array([[25, 32, 54],
       [30, 37, 46],
       [46, 50, 75]])

In [7]:
A @ B

array([[25, 32, 54],
       [30, 37, 46],
       [46, 50, 75]])

In [8]:
B.T

array([[4, 3, 3],
       [9, 1, 5],
       [1, 7, 8]])

In [9]:
A.T

array([[1, 3, 4],
       [3, 5, 9],
       [4, 1, 1]])

In [10]:
B.T @ A

array([[ 25,  54,  22],
       [ 32,  77,  42],
       [ 54, 110,  19]])

In [11]:
sys.getsizeof(2)

28

In [12]:
sys.getsizeof(100)

28

In [13]:
sys.getsizeof(0)

28

In [14]:
sys.getsizeof(10 ** 10)

32

In [15]:
sys.getsizeof(10 ** 100)

72

In [16]:
np.dtype(int).itemsize

4

In [17]:
np.dtype(np.int8).itemsize

1

In [18]:
np.dtype(float).itemsize

8