In [3]:
#Array mathematics
import numpy as np

In [5]:
a = np.array([2, 4, 2], float)
b = np.array([9, 7, 5], float)

In [7]:
#Sum The Two arrays
a + b

array([11., 11.,  7.])

In [8]:
a - b

array([-7., -3., -3.])

In [9]:
a * b

array([18., 28., 10.])

In [10]:
a / b

array([0.22222222, 0.57142857, 0.4       ])

In [11]:
b ** a

array([  81., 2401.,   25.])

In [12]:
a % b

array([2., 4., 2.])

In [13]:
a + b[np.newaxis, :]

array([[11., 11.,  7.]])

In [14]:
a + b[:, np.newaxis]

array([[11., 13., 11.],
       [ 9., 11.,  9.],
       [ 7.,  9.,  7.]])

In [15]:
np.sqrt(a)

array([1.41421356, 2.        , 1.41421356])

In [16]:
np.floor(a)

array([2., 4., 2.])

In [17]:
np.ceil(a)

array([2., 4., 2.])

In [18]:
np.rint(a)

array([2., 4., 2.])

In [19]:
np.pi

3.141592653589793

In [20]:
np.e

2.718281828459045

In [21]:
for x in a:
    print(x)

2.0
4.0
2.0


In [27]:
x = np.array([[2, 4], [3, 8], [4, 6]], int)

In [28]:
for x, y in x:
    print(x * y)

8
24
24


In [29]:
a.sum()

8.0

In [31]:
np.prod(a)

16.0

In [32]:
a.prod()

16.0

In [33]:
a.mean()

2.6666666666666665

In [34]:
a.var()

0.8888888888888888

In [35]:
a.std()

0.9428090415820634

In [36]:
a.min()

2.0

In [37]:
a.max()

4.0

In [38]:
a.argmin()

0

In [39]:
a.argmax()

1

In [40]:
a.mean(axis=0)

2.6666666666666665

In [44]:
a.max(axis=0)

4.0

In [45]:
a.min(axis=0)

2.0

In [46]:
sorted(a)

[2.0, 2.0, 4.0]

In [48]:
a.sort()

In [49]:
a

array([2., 2., 4.])

In [57]:
a.clip(2, 7)

array([2., 2., 4.])

In [54]:
np.unique(a)

array([2., 4.])

In [59]:
a > b

array([False, False, False])

In [60]:
a < b

array([ True,  True,  True])

In [61]:
a == b

array([False, False, False])

In [62]:
any(a)

True

In [63]:
all(a)

True

In [64]:
np.logical_and(a > 0, a < 3)

array([ True,  True, False])

In [65]:
np.logical_not(b)

array([False, False, False])

In [66]:
np.logical_or(a, b)

array([ True,  True,  True])

In [67]:
np.where(a != 0, 1 / a, a)

array([0.5 , 0.5 , 0.25])

In [69]:
np.where(a > 0, 1, 0)

array([1, 1, 1])

In [70]:
a.nonzero()

(array([0, 1, 2], dtype=int64),)