In [1]:
import numpy as np

In [2]:
a = np.array([2, 3, 4, 1], float)

In [3]:
a

array([2., 3., 4., 1.])

In [4]:
type(a)

numpy.ndarray

In [5]:
a[:2]

array([2., 3.])

In [6]:
a[1: 3]

array([3., 4.])

In [7]:
a[0]

2.0

In [8]:
a[2]

4.0

In [11]:
b = np.array([[1, 3, 2, 3], [2, 4, 9, 8]], float)

In [12]:
b

array([[2., 3., 2., 3.],
       [2., 4., 9., 8.]])

In [13]:
b[0, 0]

2.0

In [14]:
b[1, 3]

8.0

In [15]:
b[0, 2]

2.0

In [16]:
b[0, 1]

3.0

In [17]:
b[1, 1]

4.0

In [18]:
b[-1, -2]

9.0

In [19]:
b[-1, -1]

8.0

In [20]:
b[-1, -3]

4.0

In [21]:
b[-1, -4]

2.0

In [23]:
b[:, -2]

array([2., 9.])

In [29]:
b[-2: , -4: ]

array([[2., 3., 2., 3.],
       [2., 4., 9., 8.]])

In [31]:
b.shape

(2, 4)

In [32]:
a.shape

(4,)

In [33]:
len(a)

4

In [34]:
len(b)

2

In [35]:
2 in b

True

In [36]:
3 in a

True

In [37]:
2 in a

True

In [38]:
1 in a

True

In [39]:
8 in a

False

In [40]:
0 in b

False

In [41]:
x = np.array(range(10), float)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [42]:
x = x.reshape((5, 2))

In [43]:
x

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [44]:
y = np.array(range(20), float)
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [52]:
y = y.reshape((10, 2))

In [53]:
y

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.],
       [12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.]])

In [54]:
f = y.copy()

In [55]:
f

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.],
       [12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.]])

In [56]:
y.tolist()

[[0.0, 1.0],
 [2.0, 3.0],
 [4.0, 5.0],
 [6.0, 7.0],
 [8.0, 9.0],
 [10.0, 11.0],
 [12.0, 13.0],
 [14.0, 15.0],
 [16.0, 17.0],
 [18.0, 19.0]]

In [57]:
f.tolist()

[[0.0, 1.0],
 [2.0, 3.0],
 [4.0, 5.0],
 [6.0, 7.0],
 [8.0, 9.0],
 [10.0, 11.0],
 [12.0, 13.0],
 [14.0, 15.0],
 [16.0, 17.0],
 [18.0, 19.0]]

In [58]:
list(a)

[2.0, 3.0, 4.0, 1.0]

In [59]:
list(b)

[array([2., 3., 2., 3.]), array([2., 4., 9., 8.])]

In [60]:
a[0] = 10

In [61]:
a

array([10.,  3.,  4.,  1.])

In [66]:
s = a.tostring()

C:\Users\habob\AppData\Local\Temp\ipykernel_25328\2918348497.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s = a.tostring()


In [67]:
s

b'\x00\x00\x00\x00\x00\x00$@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\xf0?'

In [68]:
np.fromstring(s)

C:\Users\habob\AppData\Local\Temp\ipykernel_25328\4042211205.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s)


array([10.,  3.,  4.,  1.])

In [72]:
u = np.array(range(6), float).reshape((2, 3))

In [73]:
u

array([[0., 1., 2.],
       [3., 4., 5.]])

In [74]:
u.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [75]:
u.flatten()

array([0., 1., 2., 3., 4., 5.])

In [79]:
w = np.array([[2, 4, 3], [2, 4, 9]], float)
q = np.array([[2, 5, 7], [6, 9, 8]], float)

In [80]:
np.concatenate((w, q))

array([[2., 4., 3.],
       [2., 4., 9.],
       [2., 5., 7.],
       [6., 9., 8.]])

In [81]:
np.concatenate((w, q), axis = 0)

array([[2., 4., 3.],
       [2., 4., 9.],
       [2., 5., 7.],
       [6., 9., 8.]])

In [82]:
np.concatenate((w, q), axis = 1)

array([[2., 4., 3., 2., 5., 7.],
       [2., 4., 9., 6., 9., 8.]])

In [83]:
w.shape

(2, 3)

In [84]:
w[:, np.newaxis]

array([[[2., 4., 3.]],

       [[2., 4., 9.]]])

In [85]:
w[:, np.newaxis].shape

(2, 1, 3)

In [86]:
w[np.newaxis, :]

array([[[2., 4., 3.],
        [2., 4., 9.]]])

In [87]:
w[np.newaxis, :].shape

(1, 2, 3)

In [88]:
np.arange(5, dtype=float)

array([0., 1., 2., 3., 4.])

In [89]:
np.arange(5, dtype=int)

array([0, 1, 2, 3, 4])

In [90]:
np.ones((3, 2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [91]:
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [92]:
np.zeros((3, 1), dtype=float)

array([[0.],
       [0.],
       [0.]])

In [93]:
np.zeros((3, 1), dtype=int)

array([[0],
       [0],
       [0]])

In [94]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [95]:
np.ones(9, dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [96]:
np.zeros_like(a)

array([0., 0., 0., 0.])

In [97]:
np.ones_like(a)

array([1., 1., 1., 1.])

In [98]:
np.identity(3, dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
np.identity(6, dtype=float)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [100]:
np.eye(4, k=1, dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [101]:
np.eye(4, k=2, dtype=int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [102]:
np.eye(4, k=0, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [103]:
np.eye(4, k=5, dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [106]:
np.arange(1, 6, 3, dtype=int)

array([1, 4])

In [109]:
np.arange(1, 10, 4, dtype=float)

array([1., 5., 9.])