In [1]:
import numpy as np

In [3]:
a = np.array([2, 4, np.NaN, 30], float)

In [4]:
a

array([ 2.,  4., nan, 30.])

In [5]:
np.isnan(a)

array([False, False,  True, False])

In [6]:
np.isfinite(a)

array([ True,  True, False,  True])

In [29]:
b = np.array([[2, 8], [9, 19]], float)

In [30]:
b

array([[ 2.,  8.],
       [ 9., 19.]])

In [31]:
b >= 5

array([[False,  True],
       [ True,  True]])

In [32]:
b[b >= 5] #This is like the for loop, it will print the value that is true only 

array([ 8.,  9., 19.])

In [33]:
v = (b >= 5)

In [24]:
b[v] #This is just like the previous one, we just put it in a variable and then use it again

array([ 8.,  8., 19.])

In [34]:
b[np.logical_and(b > 5, b < 10)]

array([8., 9.])

In [37]:
x = np.array([[3, 1], [9, 8]], float)
y = np.array([0, 0, 1, 1, 0], int)
z = np.array([1, 1, 0, 1, 0], int)
x[y, z]

array([1., 1., 9., 8., 3.])

In [38]:
x.take(y)

array([3., 3., 1., 1., 3.])

In [39]:
x.take(z)

array([1., 1., 3., 1., 3.])

In [40]:
x.take(y, axis=0)

array([[3., 1.],
       [3., 1.],
       [9., 8.],
       [9., 8.],
       [3., 1.]])

In [41]:
x.take(z, axis=1)
#axis = 1 means column

array([[1., 1., 3., 1., 3.],
       [8., 8., 9., 8., 9.]])

In [42]:
x.take(z, axis=0)
#axis = 0 means row

array([[9., 8.],
       [9., 8.],
       [3., 1.],
       [9., 8.],
       [3., 1.]])

In [45]:
x.put([0, 3], y)

In [46]:
x

array([[0., 1.],
       [9., 0.]])

In [48]:
x.put([0, 3], 6)

In [49]:
x

array([[6., 1.],
       [9., 6.]])

In [52]:
a = np.array([3, 1, 9], float)
b = np.array([4, 8, 3], float)
np.dot(a, b)

47.0

In [53]:
np.outer(a, b)

array([[12., 24.,  9.],
       [ 4.,  8.,  3.],
       [36., 72., 27.]])

In [54]:
np.inner(a, b)
#inner like dot

47.0

In [55]:
np.median(a)

3.0

In [59]:
np.random.seed(293892)

In [61]:
np.random.rand(10)

array([0.06422734, 0.32584701, 0.75947412, 0.50300437, 0.50082124,
       0.80259791, 0.49812842, 0.99767889, 0.14153841, 0.48934197])

In [62]:
np.random.rand(3, 2)

array([[0.61822902, 0.07379226],
       [0.18801113, 0.40221117],
       [0.4835773 , 0.28870103]])

In [65]:
np.random.rand(6).reshape((2, 3))

array([[0.40177721, 0.95704449, 0.81332116],
       [0.1701638 , 0.31394497, 0.28180267]])

In [66]:
np.random.random()

0.10539050729252986

In [73]:
np.random.randint(5, 100)

17

In [75]:
np.random.poisson(6.0)

8

In [76]:
np.random.normal(1.5, 3.9)

1.840419592282659

In [77]:
np.random.normal()

2.380634242134735

In [78]:
np.random.normal(size=3)

array([ 0.08868401, -1.11252743, -0.86023051])

In [79]:
np.random.normal(size=6)

array([-1.22868821,  0.36595371,  0.63202927,  1.09771742,  0.15073174,
        1.22626524])

In [81]:
l = range(10)

In [82]:
l

range(0, 10)

In [85]:
w = range(20)

In [86]:
w

range(0, 20)